### PR TITLE
Fix create an attempt with unlimited attempts and update deprecated ModalEvents.yes

### PR DESCRIPTION
**Pull request by lamtranb**
Fix bugs:
- Cannot create attempt properly if quiz is unlimited.
- Change ModalEvents.yes to ModalEvents.save

### CODE REVIEW

**Comment by HuongNV13** [comment]
This will fix #9

**Comment by timhunt** [comment]
I was already looking at the patch when Huong's request came throught :-)

Just one general point: When you find your code has a bug like "Cannot create attempt properly if quiz is unlimited", ... well that mistake happened once, so it is clearly the sort of case that can break, and we did not have an automated test to detect it. Therefore, it would be good practice to add a test now, to make sure it never breaks again.

In fact the best practice (if you have time) is:

1. Write a test that reproduced the bug.
2. Run the test and verify that it fails.
3. Fix the bug.
4. Run the test and verify that it now passes.

Anyway, I did not hold up merging this, but something to think about next time.

**Comment by lamtranb** [comment]
Hi @timhunt,
Thanks for your advice.
I will write a behat test to cover this case and make sure it's working as expected in the next commit.

**Comment by timhunt** [comment]
:-) Great thanks.

**Pull request merged**
